# Generated by Django 6.1.1 on 2026-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='Laptop.jpg', upload_to='products/'),
            preserve_default=False,
        ),
    ]
